<a href="https://colab.research.google.com/github/Abhiraj11054/Python/blob/main/project1_template.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Libary imports can go here. As always, you can import more as needed!
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import pandas as pd

In [ ]:
# Loads the file
file = "corrupted_titanic_data.csv"
df = pd.read_csv(file)

In [ ]:
# <------------ TODO ----------------------->
# Drop all the rows with null values
# (TIP: make sure to reset the index after dropping)
df.dropna(inplace=True)
df.reset_index(drop=True,inplace=True)
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,pclass_redundant,fare_age_combination
0,1,1,female,420.0,1,0,53.284868,S,First,woman,False,C,Southampton,yes,False,1,22379.644511
1,0,1,male,54.0,0,0,51.314334,S,First,man,True,E,Southampton,no,True,1,2770.974017
2,1,2,male,34.0,0,0,13.553364,s,Second,man,True,D,Southampton,yes,True,2,460.814361
3,0,1,male,19.0,3,2,263.176986,s,First,man,True,C,Southampton,no,False,1,5000.362740
4,1,1,FEMALE,23.0,3,2,262.789833,C,First,woman,False,C,Southampton,yes,False,1,6044.166161

In [ ]:
# <------------ TODO ----------------------->
# Drop all the feature columns that you may think are not neccessary for the models evaluation
# (HINT: around 6-8 columns!)

# Columns to drop (ensure they are in lowercase)

# Drop columns safely
df = df.drop(['class', 'who', 'adult_male', 'deck', 'embark_town', 'alive', 'alone', 'pclass_redundant', 'fare_age_combination'], axis=1)

# Display cleaned dataset
df.head()

   survived  pclass     sex    age  sibsp  parch        fare embarked
0         1       1  female  420.0      1      0   53.284868        S
1         0       1    male   54.0      0      0   51.314334        S
2         1       2    male   34.0      0      0   13.553364        s
3         0       1    male   19.0      3      2  263.176986        s
4         1       1  FEMALE   23.0      3      2  262.789833        C

In [ ]:
# <------------ TODO ----------------------->
# Clean any relevant columns here
# (TIP: Pay attention to the values in the column)
df.columns = df.columns.str.lower().str.strip()
print(df.head())

   survived  pclass     sex    age  sibsp  parch        fare embarked
0         1       1  female  420.0      1      0   53.284868        S
1         0       1    male   54.0      0      0   51.314334        S
2         1       2    male   34.0      0      0   13.553364        s
3         0       1    male   19.0      3      2  263.176986        s
4         1       1  FEMALE   23.0      3      2  262.789833        C

In [ ]:
# <------------ TODO ----------------------->
# Encode all the text values to numeric ones
# (TIP: Double check your final dataframe at this point before moving on)
df['sex'] = df['sex'].map({'male': 1, 'female': 0})  # Convert "male" → 1, "female" → 0
df['embarked'] = df['embarked'].map({'S': 0, 'C': 1, 'Q': 2})  # Convert "S" → 0, "C" → 1, "Q" → 2

df.head()

   survived  pclass  sex    age  sibsp  parch        fare  embarked
0         1       1  0.0  420.0      1      0   53.284868       0.0
1         0       1  1.0   54.0      0      0   51.314334       0.0
2         1       2  1.0   34.0      0      0   13.553364       NaN
3         0       1  1.0   19.0      3      2  263.176986       NaN
4         1       1  NaN   23.0      3      2  262.789833       1.0

In [ ]:
df = df.dropna().reset_index(drop=True)

# Select features (X) and target variable (y)
X = df[['pclass', 'sex', 'age', 'sibsp', 'parch', 'fare', 'embarked']]
y = df['survived']

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Fill missing values with the mean of each column
X_train = X_train.fillna(X_train.mean())
X_test = X_test.fillna(X_train.mean())  # Use train mean to avoid data leakage

# Feature scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Train logistic regression model
model = LogisticRegression(max_iter=100)
lr = model.fit(X_train, y_train)
predictions = lr.predict(X_test)

# Print model accuracy
accuracy = accuracy_score(y_test, predictions)